version: "3.8"

services:
  web:
    image: ghcr.io/tedrob31/proyecto-r4tlabs:latest
    container_name: "r4tlabs-web"
    networks:
      - r4tlabsnet
    environment:
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - MAIN_DOMAIN=${MAIN_DOMAIN:-r4tlabs.com}
      - AUTH_DOMAIN=${AUTH_DOMAIN:-auth.r4tlabs.com}
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_OPTIONS='--max-old-space-size=1024'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/api/auth/providers"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=r4tlabsnet"
        
        # Router para los dominios
        - "traefik.http.routers.r4tlabs-web.rule=Host(`${MAIN_DOMAIN:-r4tlabs.com}`) || Host(`${AUTH_DOMAIN:-auth.r4tlabs.com}`)"
        - "traefik.http.routers.r4tlabs-web.entrypoints=websecure"
        - "traefik.http.routers.r4tlabs-web.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.r4tlabs-web.service=r4tlabs-web-service"
        
        # Servicio indicando el puerto de Next.js
        - "traefik.http.services.r4tlabs-web-service.loadbalancer.server.port=3000"

networks:
  r4tlabsnet:
    external: true
    name: r4tlabsnet
